# Generated by Django 3.0.7 on 2020-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200708_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='slideshowproject',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='slideshowproject',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
