# Generated by Django 3.0.7 on 2020-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200708_0646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='slideshowproject',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='slideshowproject',
            name='technology',
            field=models.TextField(default=''),
        ),
    ]
