# Generated by Django 3.0.7 on 2020-07-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200714_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('technology', models.TextField(default='')),
                ('image', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('video_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['project', 'order']},
        ),
        migrations.AlterModelOptions(
            name='slideshowproject',
            options={'ordering': ['order']},
        ),
    ]
